### ISSUE TITLE
disastrous parsing of human-formatted dates

### ISSUE THREAD

**Issue by alexduryee** [alexduryee/timetwister#8]
As reported by @thisismattmiller :

`timetwister "ca. mid 19th century"
[{"original_string":"ca. mid 19th century","index_dates":[3,4,5,6,7,8],"date_start":"3","date_end":"8","date_start_full":null,"date_end_full":null,"inclusive_range":true,"certainty":"approximate","test_data":"250"}]`

**Comment by alexduryee** [comment]
Resolved as of commit #30

**Comment by ablwr** [comment]
🎉 Alex is the best 🎉
